Created zoo.js, finished assignment
unioncollege-webtech/zookeep pull request #19
Opened 2016-09-16 15:26 UTC by greenitthe

2016-09-19 10:25 UTC, barberboy commented on zoo.js
> +animals.sort();
Calling `.sort()` without a compare function will not sort the animals by their first name. You will have to define a compare function and pass it to `.sort()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description

2016-09-19 10:35 UTC, barberboy commented on zoo.js
> +animals.push( new Animal("Mooney", "Blue monkey", "Cercopithecus mitis", "Smith Jungle", 2, "Blue_monkey.jpg"),
I don't mind the `Animal` function constructor—it keeps you from having to re-enter the key names (like `{name: 'Mooney', commonName: Blue monkey...}`)—but having so many parameters in a function definition is not ideal. It's kind of a mixed bag.

With JavaScript, it's more common to use an [Object literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) to define objects than to use constructor functions *unless* the object has methods.

2016-09-19 10:41 UTC, barberboy requested changes
You can decide whether or not to switch to the object literal, but please provide a compare function to the `.sort()` method to sort by the animal name.

2016-09-19 15:25 UTC, greenitthe commented
Fixed the issue. Leaving as object constructor since it would be effort to refactor and works as intended without changing. I'll keep using more object literals in mind for the future.

2016-09-21 17:55 UTC, barberboy approved these changes

2016-09-21 17:55 UTC, barberboy commented
👍 💯

2016-09-21 17:55 UTC, closed without merging